# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Teamflix Deploy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.X
        cache: 'npm'
    - name: NPM Install
      run: npm install
    - name: Angular CLI Install
      run: npm install -g @angular/cli > /dev/null
    - name: Build Test Teamflix
      run: ng build -c=production
    - name: Delete Existing Teamflix main files
      run : sudo sshpass -p ${{ secrets.NBITZ_PWD }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.NBITZ_UN }}@${{ secrets.NBITZ_HOST }} 'rm -rf /local/apps/teamflix-live/test/*'
    - name: Copy via ssh    
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/teamflix/teamflix/dist/
        remote: /local/apps/teamflix/
        host: ${{ secrets.NBITZ_HOST }}
        username: ${{ secrets.NBITZ_UN }}
        password: ${{ secrets.NBITZ_PWD }}
    - name: Deploy new Files, Restart nginx
      run : sudo sshpass -p ${{ secrets.NBITZ_PWD }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.NBITZ_UN }}@${{ secrets.NBITZ_HOST }} 'sudo systemctl restart nginx'
